// cytoscape 画布样式（编辑页与预览页共用，保证视觉一致）
import type { StylesheetJson } from 'cytoscape'
export const GRAPH_STYLE: StylesheetJson = [
  {
    selector: 'node',
    style: {
      width: 'data(w)',
      height: 'data(h)',
      'background-color': '#fff',
      'border-width': 2.2,
      'border-color': '#94a3a3',
      'border-style': 'solid',
      label: 'data(name)',
      color: '#172126',
      'font-size': 12.5,
      'font-weight': 700,
      'text-valign': 'center',
      'text-halign': 'center',
      'text-wrap': 'wrap',
      'text-max-width': 'data(w)',
      'overlay-opacity': 0,
    },
  },
  { selector: '[type = "实体"]', style: { 'background-color': '#e9f2ff', 'border-color': '#3978c5', shape: 'round-rectangle' } },
  { selector: '[type = "属性"]', style: { 'background-color': '#fff0f7', 'border-color': '#d15e9a', shape: 'ellipse' } },
  { selector: '[type = "规则"]', style: { 'background-color': '#edf9f1', 'border-color': '#35a167', shape: 'round-rectangle' } },
  { selector: 'node:selected', style: { 'border-color': '#245cdf', 'border-width': 4.2 } },
  { selector: 'node.link-src', style: { 'border-style': 'dashed', 'border-color': '#9bb2ac', 'border-width': 1.8 } },
  { selector: 'node.search-hit', style: { 'border-color': '#0b7ec2', 'border-width': 4.5, 'z-index': 20 } },
  { selector: 'node.search-focus', style: { 'border-color': '#245cdf', 'border-width': 5.2, 'z-index': 25 } },
  { selector: 'node.dim', style: { opacity: 0.09 } },
  {
    selector: 'edge',
    style: {
      width: 1.5,
      'curve-style': 'bezier',
      'line-color': '#4d7770',
      'line-opacity': 0.45,
      'target-arrow-shape': 'triangle',
      'target-arrow-color': '#657d78',
      'target-arrow-fill': 'filled',
      'arrow-scale': 0.7,
      label: 'data(relation)',
      'font-size': 10.5,
      color: '#87500f',
      'font-weight': 600,
      'text-outline-color': '#fff',
      'text-outline-width': 3,
      'text-outline-opacity': 1,
      'overlay-opacity': 0,
    },
  },
  { selector: 'edge:selected', style: { 'line-color': '#245cdf', 'line-opacity': 0.98, 'target-arrow-color': '#245cdf', width: 2.6 } },
  { selector: 'edge.hovered', style: { 'line-color': '#245cdf', 'line-opacity': 0.98, 'target-arrow-color': '#245cdf', width: 2.6 } },
  { selector: 'edge.dim', style: { opacity: 0.08 } },
]

// 预览查看器专用样式（移植自旧版 kq-editor 静态预览页）：
// 浅色填充 + 边框色的节点、选中/追踪蓝色高亮（上游 #245cdf、下游 #1a49b0）、上游/下游/淡出分类、关系作用域高亮
export const PREVIEW_GRAPH_STYLE = [
  {
    selector: 'node',
    style: {
      width: 'data(w)',
      height: 'data(h)',
      'background-color': '#fff',
      'border-width': 2.2,
      'border-color': '#94a3a3',
      'border-style': 'solid',
      label: 'data(name)',
      color: '#172126',
      'font-size': 12.5,
      'font-weight': 700,
      'text-valign': 'center',
      'text-halign': 'center',
      'text-wrap': 'wrap',
      'text-max-width': 'data(w)',
      'overlay-opacity': 0,
    },
  },
  { selector: '[type = "实体"]', style: { 'background-color': '#e9f2ff', 'border-color': '#3978c5', shape: 'round-rectangle' } },
  { selector: '[type = "属性"]', style: { 'background-color': '#fff0f7', 'border-color': '#d15e9a', shape: 'ellipse' } },
  { selector: '[type = "规则"]', style: { 'background-color': '#edf9f1', 'border-color': '#35a167', shape: 'round-rectangle' } },
  { selector: 'node:selected', style: { 'border-color': '#245cdf', 'border-width': 4.2 } },
  { selector: 'node.ghost', style: { 'border-style': 'dashed', 'border-color': '#9bb2ac', 'border-width': 1.8 } },
  {
    selector: 'edge',
    style: {
      width: 1.5,
      'curve-style': 'bezier',
      'line-color': '#4d7770',
      'line-opacity': 0.45,
      'target-arrow-shape': 'triangle',
      'target-arrow-color': '#657d78',
      'target-arrow-fill': 'filled',
      'arrow-scale': 0.7,
      label: 'data(relation)',
      'font-size': 10.5,
      color: '#87500f',
      'font-weight': 600,
      'text-outline-color': '#fff',
      'text-outline-width': 3,
      'text-outline-opacity': 1,
      'overlay-opacity': 0,
    },
  },
  { selector: 'edge:selected', style: { 'line-color': '#245cdf', 'line-opacity': 0.98, 'target-arrow-color': '#245cdf', width: 2.6 } },
  { selector: 'node.anc', style: { 'border-color': '#245cdf', 'border-width': 3.0 } },
  { selector: 'node.desc', style: { 'border-color': '#1a49b0', 'border-width': 2.8 } },
  { selector: 'node.dim', style: { opacity: 0.09 } },
  { selector: 'edge.trace', style: { 'line-color': '#245cdf', 'line-opacity': 0.98, 'target-arrow-color': '#245cdf', width: 2.6 } },
  { selector: 'edge.down', style: { 'line-color': '#1a49b0', 'line-opacity': 0.98, 'target-arrow-color': '#1a49b0', width: 2.6 } },
  { selector: 'edge.dim', style: { opacity: 0.08 } },
  { selector: 'edge.hovered', style: { 'line-color': '#245cdf', 'line-opacity': 0.98, 'target-arrow-color': '#245cdf', width: 2.6 } },
]
