// cytoscape 画布样式（自旧仓库复制；类型选择器扩展为当前五类，其余逐行保留）
export const GRAPH_STYLE = [
  {
    selector: 'node',
    style: {
      width: 'data(w)',
      height: 'data(h)',
      'background-color': '#fff',
      'border-width': 2.2,
      'border-color': '#94a3a3',
      'border-style': 'solid',
      label: 'data(name)',
      color: '#172126',
      'font-size': 12.5,
      'font-weight': 700,
      'text-valign': 'center',
      'text-halign': 'center',
      'text-wrap': 'wrap',
      'text-max-width': 'data(w)',
      'overlay-opacity': 0,
    },
  },
  { selector: '[type = "对象"]', style: { 'background-color': '#e9f2ff', 'border-color': '#3978c5', shape: 'round-rectangle' } },
  { selector: '[type = "共享属性"]', style: { 'background-color': '#fff0f7', 'border-color': '#d15e9a', shape: 'ellipse' } },
  { selector: '[type = "私有属性"]', style: { 'background-color': '#fdf3e4', 'border-color': '#d18f3c', shape: 'ellipse' } },
  { selector: '[type = "规则"]', style: { 'background-color': '#edf9f1', 'border-color': '#35a167', shape: 'round-rectangle' } },
  { selector: '[type = "动作"]', style: { 'background-color': '#f2eeff', 'border-color': '#7a5fb5', shape: 'round-rectangle' } },
  { selector: 'node:selected', style: { 'border-color': '#f59b23', 'border-width': 4.2 } },
  { selector: 'node.link-src', style: { 'border-style': 'dashed', 'border-color': '#9bb2ac', 'border-width': 1.8 } },
  { selector: 'node.search-hit', style: { 'border-color': '#0b7ec2', 'border-width': 4.5, 'z-index': 20 } },
  { selector: 'node.search-focus', style: { 'border-color': '#e8801a', 'border-width': 5.2, 'z-index': 25 } },
  { selector: 'node.dim', style: { opacity: 0.09 } },
  {
    selector: 'edge',
    style: {
      width: 1.5,
      'curve-style': 'bezier',
      'line-color': '#4d7770',
      'line-opacity': 0.45,
      'target-arrow-shape': 'triangle',
      'target-arrow-color': '#657d78',
      'target-arrow-fill': 'filled',
      'arrow-scale': 0.7,
      label: 'data(relation)',
      'font-size': 10.5,
      color: '#87500f',
      'font-weight': 600,
      'text-outline-color': '#fff',
      'text-outline-width': 3,
      'text-outline-opacity': 1,
      'overlay-opacity': 0,
    },
  },
  { selector: 'edge:selected', style: { 'line-color': '#0c6b58', 'line-opacity': 0.98, 'target-arrow-color': '#0c6b58', width: 2.6 } },
  { selector: 'edge.hovered', style: { 'line-color': '#0c6b58', 'line-opacity': 0.98, 'target-arrow-color': '#0c6b58', width: 2.6 } },
  { selector: 'edge.dim', style: { opacity: 0.08 } },
]

// 预览查看器专用样式（移植自旧版 kq-editor 静态预览页）：
// 浅色填充 + 边框色的节点、选中橙色高亮、上游/下游/淡出分类、关系作用域高亮
export const PREVIEW_GRAPH_STYLE = [
  {
    selector: 'node',
    style: {
      width: 'data(w)',
      height: 'data(h)',
      'background-color': '#fff',
      'border-width': 2.2,
      'border-color': '#94a3a3',
      'border-style': 'solid',
      label: 'data(name)',
      color: '#172126',
      'font-size': 12.5,
      'font-weight': 700,
      'text-valign': 'center',
      'text-halign': 'center',
      'text-wrap': 'wrap',
      'text-max-width': 'data(w)',
      'overlay-opacity': 0,
    },
  },
  { selector: '[type = "对象"]', style: { 'background-color': '#e9f2ff', 'border-color': '#3978c5', shape: 'round-rectangle' } },
  { selector: '[type = "共享属性"]', style: { 'background-color': '#fff0f7', 'border-color': '#d15e9a', shape: 'ellipse' } },
  { selector: '[type = "私有属性"]', style: { 'background-color': '#fdf3e4', 'border-color': '#d18f3c', shape: 'ellipse' } },
  { selector: '[type = "规则"]', style: { 'background-color': '#edf9f1', 'border-color': '#35a167', shape: 'round-rectangle' } },
  { selector: '[type = "动作"]', style: { 'background-color': '#f2eeff', 'border-color': '#7a5fb5', shape: 'round-rectangle' } },
  { selector: 'node:selected', style: { 'border-color': '#f59b23', 'border-width': 4.2 } },
  { selector: 'node.ghost', style: { 'border-style': 'dashed', 'border-color': '#9bb2ac', 'border-width': 1.8 } },
  {
    selector: 'edge',
    style: {
      width: 1.5,
      'curve-style': 'bezier',
      'line-color': '#4d7770',
      'line-opacity': 0.45,
      'target-arrow-shape': 'triangle',
      'target-arrow-color': '#657d78',
      'target-arrow-fill': 'filled',
      'arrow-scale': 0.7,
      label: 'data(relation)',
      'font-size': 10.5,
      color: '#87500f',
      'font-weight': 600,
      'text-outline-color': '#fff',
      'text-outline-width': 3,
      'text-outline-opacity': 1,
      'overlay-opacity': 0,
    },
  },
  { selector: 'edge:selected', style: { 'line-color': '#0c6b58', 'line-opacity': 0.98, 'target-arrow-color': '#0c6b58', width: 2.6 } },
  { selector: 'node.anc', style: { 'border-color': '#b46b1c', 'border-width': 3.0 } },
  { selector: 'node.desc', style: { 'border-color': '#278b6b', 'border-width': 2.8 } },
  { selector: 'node.dim', style: { opacity: 0.09 } },
  { selector: 'edge.trace', style: { 'line-color': '#b46b1c', 'line-opacity': 0.98, 'target-arrow-color': '#b46b1c', width: 2.6 } },
  { selector: 'edge.down', style: { 'line-color': '#278b6b', 'line-opacity': 0.98, 'target-arrow-color': '#278b6b', width: 2.6 } },
  { selector: 'edge.dim', style: { opacity: 0.08 } },
  { selector: 'edge.hovered', style: { 'line-color': '#0c6b58', 'line-opacity': 0.98, 'target-arrow-color': '#0c6b58', width: 2.6 } },
]

// 多图谱预览画布样式（由 wiz_kq_builder_view 移植）：
// 语义节点沿用预览页配色，另含组根节点 / ＋−徽标 / 软连接 / 搜索态
export const MULTI_PREVIEW_STYLE = [
  {
    selector: 'node',
    style: {
      width: 'data(w)',
      height: 'data(h)',
      'background-color': '#fff',
      'border-width': 2.2,
      'border-color': '#94a3a3',
      'border-style': 'solid',
      label: 'data(name)',
      color: '#172126',
      'font-size': 12.5,
      'font-weight': 700,
      'text-valign': 'center',
      'text-halign': 'center',
      'text-wrap': 'wrap',
      'text-max-width': 'data(w)',
      'overlay-opacity': 0,
    },
  },
  { selector: '[type = "实体"]', style: { 'background-color': '#e9f2ff', 'border-color': '#3978c5', shape: 'round-rectangle' } },
  { selector: '[type = "属性"]', style: { 'background-color': '#fff0f7', 'border-color': '#d15e9a', shape: 'ellipse' } },
  { selector: '[type = "规则"]', style: { 'background-color': '#edf9f1', 'border-color': '#35a167', shape: 'round-rectangle' } },

  // ---- 组根节点（图谱折叠态/展开态锚点） ----
  {
    selector: 'node.root',
    style: {
      'background-color': '#eef7f3',
      'border-color': '#14705d',
      'border-width': 3,
      shape: 'round-rectangle',
      label: 'data(label)',
      color: '#123f36',
      'font-size': 12,
      'font-weight': 700,
      'text-wrap': 'wrap',
      'text-max-width': 'data(w)',
      'text-valign': 'center',
      'text-halign': 'center',
    },
  },
  { selector: 'node.root.expanded', style: { 'border-color': '#e8801a' } },
  { selector: 'node.root:selected', style: { 'border-color': '#f59b23', 'border-width': 4.2 } },

  // ---- ＋/− 徽标（点击展开/折叠） ----
  {
    selector: 'node.badge',
    style: {
      width: 22,
      height: 22,
      shape: 'ellipse',
      'background-color': '#14705d',
      'border-width': 0,
      label: 'data(label)',
      color: '#ffffff',
      'font-size': 15,
      'font-weight': 800,
      'text-valign': 'center',
      'text-halign': 'center',
      'text-wrap': 'none',
      grabbable: false,
      'z-index': 30,
      'overlay-opacity': 0,
    },
  },
  { selector: 'node.badge.expanded', style: { 'background-color': '#e8801a' } },

  { selector: 'node:selected', style: { 'border-color': '#f59b23', 'border-width': 4.2 } },
  { selector: 'node.search-hit', style: { 'border-color': '#0b7ec2', 'border-width': 4.5, 'z-index': 20 } },
  { selector: 'node.dim', style: { opacity: 0.12 } },

  {
    selector: 'edge',
    style: {
      width: 1.5,
      'curve-style': 'bezier',
      'line-color': '#4d7770',
      'line-opacity': 0.45,
      'target-arrow-shape': 'triangle',
      'target-arrow-color': '#657d78',
      'target-arrow-fill': 'filled',
      'arrow-scale': 0.7,
      label: 'data(relation)',
      'font-size': 10.5,
      color: '#87500f',
      'font-weight': 600,
      'text-outline-color': '#fff',
      'text-outline-width': 3,
      'text-outline-opacity': 1,
      'overlay-opacity': 0,
    },
  },
  // 根 → 实体的思维导图软连接（虚线、无箭头、无文字）
  {
    selector: 'edge.group-link',
    style: {
      'line-style': 'dashed',
      'line-color': '#8fa8a2',
      'line-opacity': 0.7,
      width: 1.6,
      'target-arrow-shape': 'none',
      label: '',
    },
  },
  { selector: 'edge:selected', style: { 'line-color': '#0c6b58', 'line-opacity': 0.98, 'target-arrow-color': '#0c6b58', width: 2.6 } },
  { selector: 'edge.dim', style: { opacity: 0.06 } },
]
