<script setup lang="ts">
import {graphReferences} from '../ontology/editorModel'
// removed unused import
import {ref,computed,watch} from 'vue'
import { appConfirm } from '../shared/appConfirm'
import EditorLayout from '../shared/EditorLayout.vue'
import Field from '../shared/EditorField.vue'
import SourceReference from '../ontology/SourceReference.vue'
const props=defineProps({state:Object,kind:String,projectState:Object,focusId:String,returnTo:Object});const emit=defineEmits(['before-change','changed','navigate'])
// S4（20260920 验收）：从资产库外部依赖「去处理」跳入时携带来源定义上下文（returnTo），
// 页头「← 返回接口「x」」回到原定义继续操作；聚焦接口定义本身仍走 focusId 选中，不自动删除。
function backToSource(){const r=props.returnTo as any;if(!r)return;emit('navigate',r.view,{...(r.focus||{}),openUsages:true})}
const query=ref(''),tab=ref('business')
const selected=ref(''),result=ref(null),message=ref(''),busy=ref(false),objects=ref([]),parameters=ref({}),_newProperty=ref('')
const rows=computed(()=>props.state.workflow[props.kind]),item=computed(()=>rows.value.find(n=>n.id===selected.value))
const graph=computed(()=>props.state.ontology['@graph']),types=computed(()=>graph.value.filter(n=>n['@type']==='owl:Class')),shared=computed(()=>graph.value.filter(n=>n['@type']==='mg:SharedProperty')),relations=computed(()=>graph.value.filter(n=>n['@type']==='owl:ObjectProperty'))
const labels={functions:'计算定义',actions:'动作定义',interfaces:'接口定义'}
watch(rows,v=>{if(!v.some(n=>n.id===selected.value))selected.value=v[0]?.id||''},{immediate:true})
watch([selected,()=>props.kind],()=>{result.value=null;message.value='';parameters.value={};objects.value=[];tab.value='business'})
watch(()=>props.focusId,id=>{if(id&&rows.value.some(n=>n.id===id)){query.value='';selected.value=id}},{immediate:true})
function before(){emit('before-change')}
function changed(){result.value=null;emit('changed')}
function mutate(fn){before();fn();changed()}
function update(k,v){item.value[k]=v;changed()}
const list=computed(()=>rows.value.filter(r=>(r.name||'').includes(query.value.trim())).map(r=>({id:r.id,name:r.name||('未命名'+labels[props.kind]+' '+(rows.value.indexOf(r)+1)),meta:props.kind==='interfaces'?`${r.implementations.length} 类对象实现`:props.kind==='functions'?applicableTypes(r).map(title).join('、'):title(r.object_type),note:props.kind==='interfaces'?'共享契约':r.implementation_ref?'登记了实现，试运行时核对契约':'业务定义 · 待开发实现'})))
const applicableTypes=r=>Array.isArray(r.object_types)?r.object_types:(r.object_type?[r.object_type]:[])
function toggleType(value:string,event:Event){mutate(()=>{const ids=applicableTypes(item.value);item.value.object_types=(event.target as HTMLInputElement).checked?[...ids,value]:ids.filter(id=>id!==value);delete item.value.object_type})}
const objectOptions=computed(()=>types.value.map(t=>({value:t['@id'].slice(3),label:t['rdfs:label']})))
const paramTypes=[{value:'object',label:'对象'},{value:'string',label:'文本'},{value:'double',label:'数值'},{value:'integer',label:'整数'},{value:'boolean',label:'是／否'},{value:'timestamp',label:'日期时间'}]
function create(){query.value='';tab.value='business';mutate(()=>{const n={id:crypto.randomUUID(),name:'',description:'',status:'experimental'};if(props.kind==='interfaces')Object.assign(n,{properties:[],implementations:[]});else Object.assign(n,{object_type:types.value[0]?.['@id'].slice(3)||'',inputs:[],acceptance:'',implementation_ref:'',...(props.kind==='functions'?{logic:''}:{effect:'',criteria:'',permission:'',relation_ref:''})});rows.value.push(n);selected.value=n.id})}
async function remove(){const refs=graphReferences(props.state,selected.value);if(refs.length){message.value='暂不能删除：请先处理引用（'+refs.join('、')+'）。';return}if(await appConfirm({ message: '删除当前定义？此页面不支持撤销，删除后需重新创建。', danger: true }))mutate(()=>{rows.value.splice(rows.value.indexOf(item.value),1)})}
function addInput(){mutate(()=>item.value.inputs.push({name:'',type:'string',object_type:'',description:'',required:true}))}
import { demoObjects, functionPreview, actionPreview } from '../ontology/api'
const REQUESTS:Record<string,(p:any)=>Promise<any>>={'demo-objects':demoObjects,'function-preview':functionPreview,'action-preview':actionPreview}
// 422 返回结构化 errors[]（定义缺失/不匹配），与网络/5xx 一样抛出，由调用方 message 展示
async function request(path,extra={}){const d=await REQUESTS[path]({state:props.state,projectState:props.projectState||undefined,...extra});if(d.errors?.length)throw Error(d.errors?.join('；')||'请求失败');return d}
async function loadObjects(){busy.value=true;try{objects.value=(await request('demo-objects')).objects;for(const p of item.value.inputs)if(p.type==='object')parameters.value[p.name]=objects.value.find(o=>o.type===p.object_type && (p.name!=='system'||o.id.endsWith(':north')))?.id||'';else if(p.type==='timestamp')parameters.value[p.name]='2026-09-08T10:00:00+08:00';message.value='已加载模拟实例'}catch(e){message.value=e.message}finally{busy.value=false}}
async function run(){busy.value=true;message.value='';try{result.value=await request(props.kind==='functions'?'function-preview':'action-preview',{definitionId:item.value.id,parameters:parameters.value})}catch(e){message.value=e.message}finally{busy.value=false}}
const title=id=>types.value.find(t=>t['@id']==='mg:'+id)?.['rdfs:label']||id
function missing(t){return item.value.properties.filter(id=>!graph.value.some(p=>p['@type']==='owl:DatatypeProperty'&&p['rdfs:domain']?.['@id']==='mg:'+t&&p['mg:sharedProperty']?.['@id']===id)).map(id=>shared.value.find(s=>s['@id']===id)?.['rdfs:label']||id)}

</script>
<template><EditorLayout :title="labels[kind]" :subtitle="kind==='functions'?'业务专家描述怎样计算，开发负责实现。没有计算需求时可跳过。':kind==='actions'?'业务专家定义修改效果与条件，开发实施权限和执行。只读场景可跳过。':'共同使用多种对象时再定义接口；不是 HTTP 接口。'" :items="list" :selected="selected" v-model:search="query" :create-label="'新建'+labels[kind]" @create="create" @select="selected=$event"><template #actions><button v-if="returnTo" type="button" @click="backToSource">← 返回{{returnTo.label}}</button></template>
<section v-if="item" class="card detail-card" :key="item.id"><div class="detail-heading"><div><span class="eyebrow">{{labels[kind]}}</span><h2>{{item.name||'填写新定义'}}</h2></div><span class="status-pill">{{kind==='interfaces'?'定义维护':item.implementation_ref?'已登记实现':'待开发实现'}}</span></div><div v-if="kind!=='functions'" class="editor-tabs"><button :class="{active:tab==='business'}" @click="tab='business'">业务定义</button><button v-if="kind!=='interfaces'" :class="{active:tab==='inputs'}" @click="tab='inputs'">输入与输出</button><button v-if="kind!=='interfaces'" :class="{active:tab==='preview'}" @click="tab='preview'">验收与试运行</button><button :class="{active:tab==='technical'}" @click="tab='technical'">开发交接</button></div>
<div v-show="tab==='business'"><div class="fill-hint">填写名称、用途和业务规则。原始资料可在下方展开参考，未确认的口径请明确标注。</div><Field label="名称" :model-value="item.name" required :example="kind==='functions'?'计算系统SOC':kind==='actions'?'调整设备所属系统':'SOC信息对象'" @before-change="before" @update:model-value="update('name',$event)"/><Field label="业务描述" type="textarea" :model-value="item.description" required :example="kind==='functions'?'查询指定系统、指定时刻的SOC，并解释来源。':kind==='actions'?'更正或调整设备的系统归属。':'统一读取系统、设备和簇的SOC信息。'" @before-change="before" @update:model-value="update('description',$event)"/>
<fieldset v-if="kind==='functions'" class="sample-panel"><legend>适用对象类型 *</legend><p class="field-help">可多选，至少选择一项；所选对象共用本计算口径。</p><div class="choice-grid"><label v-for="option in objectOptions" :key="option.value" class="check-option"><input type="checkbox" :checked="applicableTypes(item).includes(option.value)" @change="toggleType(option.value,$event)">{{option.label}}</label></div><p v-if="!applicableTypes(item).length" class="inline-error">请至少选择一个适用对象类型。</p></fieldset>
<Field v-if="kind==='actions'" label="适用对象类型" type="select" :options="objectOptions" :model-value="item.object_type" required @before-change="before" @update:model-value="update('object_type',$event)"/>
<template v-if="kind==='functions'"><Field label="计算口径" type="textarea" :model-value="item.logic" required example="Σ(簇SOC × 同口径容量基准) ÷ Σ容量基准。" help="说明输入之间的关系和权重依据；不是在这里编写程序。" @before-change="before" @update:model-value="update('logic',$event)"/></template>
<template v-if="kind==='actions'"><Field label="变更效果" type="textarea" :model-value="item.effect" required example="结束原系统归属、建立新归属；保留历史有效期。" @before-change="before" @update:model-value="update('effect',$event)"/><Field label="相关链接类型" type="select" :model-value="item.relation_ref" :options="[{value:'',label:'不关联'},...relations.map(r=>({value:r['@id'],label:r['rdfs:label']}))]" @before-change="before" @update:model-value="update('relation_ref',$event)"/><Field label="提交条件" type="textarea" :model-value="item.criteria" required example="设备和系统存在、新旧系统不同、无冲突归属。" @before-change="before" @update:model-value="update('criteria',$event)"/><Field label="权限与审批要求" type="textarea" :model-value="item.permission" required example="由资产管理员调整；谁能提出、批准和执行需要项目确认。" help="此处保存业务要求；实际身份、权限和审批由开发实施。" @before-change="before" @update:model-value="update('permission',$event)"/></template>
<template v-if="kind==='interfaces'"><h3 class="section-heading">必需共享属性 <span>选择共同契约</span></h3><div class="choice-grid"><label v-for="p in shared" :key="p['@id']" class="check-option"><input type="checkbox" v-model="item.properties" :value="p['@id']" @click="before" @change="changed"><span>{{p['rdfs:label']}}</span></label></div><p v-if="!shared.length" class="empty">先在属性管理中建立共享属性。</p><h3 class="section-heading">实现此接口的对象类型</h3><label v-for="t in types" :key="t['@id']" class="check-option"><input type="checkbox" v-model="item.implementations" :value="t['@id'].slice(3)" @click="before" @change="changed"><span>{{t['rdfs:label']}}</span></label><p v-for="t in item.implementations" :key="t" :class="missing(t).length?'inline-error':'inline-success'">{{title(t)}}：{{missing(t).length?'尚缺少 '+missing(t).join('、'):'满足已选属性契约'}}</p><p class="field-help">当前仅校验共享属性契约。链接／动作约束尚未实现，不强制各对象使用相同算法。</p></template>
<SourceReference :ids="item.source_ids" :note="item.review_note"/><div v-if="kind==='actions'" class="next-step"><button @click="tab='inputs'">继续填写输入与输出 →</button></div></div>
<div v-if="kind==='actions'" v-show="tab==='inputs'"><div class="fill-hint">业务专家描述需要什么输入；参数名和类型由开发补充。对象参数请选择其对应类型。</div><div class="panelhead"><h3>输入参数 · {{item.inputs.length}}</h3><button @click="addInput">＋ 添加参数</button></div><div v-for="(p,i) in item.inputs" :key="i" class="parameter-card"><div class="panelhead"><strong>参数 {{Number(i)+1}} · {{p.description||'待填写'}}</strong><button class="row-link danger" @click="mutate(()=>item.inputs.splice(i,1))">移除参数</button></div><div class="form-grid"><Field label="参数名称" v-model="p.name" required example="object_id" @before-change="before" @update:model-value="changed"/><Field label="参数类型" type="select" v-model="p.type" :options="paramTypes" required @before-change="before" @update:model-value="changed"/></div><Field v-if="p.type==='object'" label="参数对象类型" v-model="p.object_type" type="select" :options="objectOptions" required @before-change="before" @update:model-value="changed"/><Field label="参数说明" v-model="p.description" example="要查询的储能系统。" @before-change="before" @update:model-value="changed"/><label class="check-option"><input type="checkbox" v-model="p.required" @click="before" @change="changed">调用时必填</label></div><p v-if="!item.inputs.length" class="empty">没有输入参数；需要用户指定对象或时间时，请添加。</p>
</div>
<div v-if="kind==='actions'" v-show="tab==='preview'"><Field label="验收案例" type="textarea" :model-value="item.acceptance" required example="设备A从系统一转到系统二；权限不足时拒绝。" @before-change="before" @update:model-value="update('acceptance',$event)"/><div class="sample-panel"><h3>模拟变更预览</h3><p v-if="!item.implementation_ref">此项目前只有业务定义，尚未接入实现。填写验收案例后交由开发；不是所有定义都能试运行。</p><template v-else><p>使用内置模拟数据；修改算法、参数或动作效果后，需重新匹配实现。动作预览不写入实例。</p><button :disabled="busy" @click="loadObjects">加载示例参数</button><div v-for="p in item.inputs" :key="p.name"><Field v-if="p.type==='object'" :label="p.description||p.name" v-model="parameters[p.name]" type="select" :options="objects.filter(o=>o.type===p.object_type).map(o=>({value:o.id,label:o.display_name||o.properties.name||o.id}))"/><Field v-else :label="p.description||p.name" v-model="parameters[p.name]" :example="p.type==='timestamp'?'2026-09-08T10:00:00+08:00':''"/></div><button class="primary" :disabled="busy" @click="run">{{busy?'处理中…':'预览变更'}}</button></template><div v-if="result?.result"><div class="result">{{result.result.value??'—'}}<small>{{result.result.unit}}</small></div><p>{{result.result.reason||'有效结果'}}</p><details><summary>计算来源</summary><pre>{{JSON.stringify(result.result.lineage,null,2)}}</pre></details></div><div v-if="result?.dry_run" class="inline-success"><p>原归属：{{result.before}}</p><p>新归属：{{result.after}}</p>仅预览，未执行变更。</div></div></div>
<div v-if="kind!=='functions'" v-show="tab==='technical'"><div class="fill-hint">开发／实施补充。业务专家可以先完成业务定义。</div><Field label="生命周期" :model-value="item.status" type="select" :options="[{value:'experimental',label:'草拟／实验中'},{value:'active',label:'使用中'},{value:'deprecated',label:'已弃用'}]" help="定义状态不代表运行能力。" @before-change="before" @update:model-value="update('status',$event)"/><Field v-if="kind!=='interfaces'" label="实现引用" :model-value="item.implementation_ref" example="由开发登记实现版本" help="填写字符串不会加载程序；实际试运行会检查是否有匹配实现。" @before-change="before" @update:model-value="update('implementation_ref',$event)"/></div><p v-if="message" :class="message.startsWith('已')?'inline-success':'inline-error'" role="status">{{message}}</p><div class="detail-footer"><span>修改后自动保存到本体草稿</span><button class="danger-btn" @click="remove">删除定义</button></div></section><section v-else class="card"><div class="empty-state"><div class="empty-state-ico">◇</div><p>还没有{{labels[kind]}}；选择一项定义，或按业务需要新建。</p><button class="primary" @click="create">新建{{labels[kind]}}</button></div></section></EditorLayout></template>
