<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import AppSelect from '../shared/AppSelect.vue'
import {coordinate} from './explorerModel'
import type {ExplorerObject} from './explorerTypes'
const props=defineProps<{objects:ExplorerObject[]}>(),emit=defineEmits<{select:[id:string]}>()
const lat=ref(''),lon=ref('')
const keys=computed(()=>[...new Set(props.objects.flatMap(o=>Object.keys(o.properties)))])
watch(keys,k=>{if(!k.includes(lat.value))lat.value=k.find(v=>/^(latitude|lat|纬度)$/i.test(v))||'';if(!k.includes(lon.value))lon.value=k.find(v=>/^(longitude|lon|lng|经度)$/i.test(v))||''},{immediate:true})
const points=computed(()=>props.objects.flatMap(o=>{if(!lat.value||!lon.value)return [];const y=coordinate(o.properties[lat.value],-90,90),x=coordinate(o.properties[lon.value],-180,180);return x===null||y===null?[]:[{o,lat:y,lon:x}]}))
const extent=computed(()=>{if(!points.value.length)return {west:-180,east:180,south:-90,north:90};const xs=points.value.map(p=>p.lon),ys=points.value.map(p=>p.lat),dx=Math.max(.01,Math.max(...xs)-Math.min(...xs)),dy=Math.max(.01,Math.max(...ys)-Math.min(...ys));return {west:Math.min(...xs)-dx*.2,east:Math.max(...xs)+dx*.2,south:Math.min(...ys)-dy*.2,north:Math.max(...ys)+dy*.2}})
const xy=(p:{lat:number;lon:number})=>({x:60+(p.lon-extent.value.west)/(extent.value.east-extent.value.west)*620,y:330-(p.lat-extent.value.south)/(extent.value.north-extent.value.south)*280})
</script>
<template><section class="card location"><h3>地理分布</h3><p class="muted">离线经纬度视图；选择坐标属性后显示对象位置，不加载外部地图底图。</p><div class="coordinate-fields"><label>纬度属性<AppSelect v-model="lat" aria-label="纬度属性" :options="[{value:'',label:'请选择纬度属性'},...keys.map(k=>({value:k,label:objects.find(o=>o.propertyLabels[k])?.propertyLabels[k]||k}))]"/></label><label>经度属性<AppSelect v-model="lon" aria-label="经度属性" :options="[{value:'',label:'请选择经度属性'},...keys.map(k=>({value:k,label:objects.find(o=>o.propertyLabels[k])?.propertyLabels[k]||k}))]"/></label></div><div v-if="!points.length" class="empty"><strong>当前没有可展示的坐标</strong><p>请在项目数据映射中接入经度、纬度属性。当前储能模拟数据没有位置字段。</p></div><template v-else><p>{{points.length}} 个有效坐标 · {{objects.length-points.length}} 个对象未展示（缺值或超出经纬度范围）</p><svg viewBox="0 0 740 390" role="img" aria-label="对象经纬度分布图"><rect x="60" y="50" width="620" height="280" fill="#f3f7fc" stroke="#c8d8eb"/><g v-for="i in [0,1,2,3,4]" :key="i"><line :x1="60+i*155" y1="50" :x2="60+i*155" y2="330" stroke="#d8e3f0"/><line x1="60" :y1="50+i*70" x2="680" :y2="50+i*70" stroke="#d8e3f0"/><text :x="60+i*155" y="355" text-anchor="middle">{{(extent.west+(extent.east-extent.west)*i/4).toFixed(4)}}°</text><text x="50" :y="55+i*70" text-anchor="end">{{(extent.north-(extent.north-extent.south)*i/4).toFixed(4)}}°</text></g><g v-for="p in points" :key="p.o.id"><circle :cx="xy(p).x" :cy="xy(p).y" r="7" fill="#346fe1" tabindex="0" role="button" :aria-label="p.o.name" @click="emit('select',p.o.id)" @keydown.enter="emit('select',p.o.id)"><title>{{p.o.name}} · {{p.lat}}, {{p.lon}}</title></circle><text :x="xy(p).x" :y="xy(p).y-12" text-anchor="middle">{{p.o.name}}</text></g><text x="360" y="380">经度</text><text x="15" y="30">纬度</text></svg></template></section></template>
<style scoped>.coordinate-fields{display:flex;gap:20px}.coordinate-fields label{flex:1;min-width:0}.location svg{width:100%;min-height:280px}.location text{font-size:12px;fill:#496179}.location circle{cursor:pointer}@media(max-width:600px){.coordinate-fields{display:block}}</style>
