<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import AppSelect from '../shared/AppSelect.vue'
import type {ExplorerObject,ExplorerObservation} from './explorerTypes'
const props=defineProps<{objects:ExplorerObject[];observations:ExplorerObservation[]}>()
const emit=defineEmits<{select:[id:string]}>()
const mode=ref('count'),field=ref(''),other=ref(''),subject=ref(''),goodOnly=ref(true)
const numeric=computed(()=>[...new Set(props.objects.flatMap(o=>Object.entries(o.properties).filter(([,v])=>typeof v==='number'&&Number.isFinite(v)).map(([k])=>k)))])
const options=computed(()=>numeric.value.map(k=>({value:k,label:props.objects.find(o=>o.propertyLabels[k])?.propertyLabels[k]||k})))
watch(numeric,keys=>{if(!keys.includes(field.value))field.value=keys[0]||'';if(!keys.includes(other.value))other.value=keys[1]||keys[0]||''},{immediate:true})
const observedObjects=computed(()=>props.objects.filter(o=>props.observations.some(r=>r.objectId===o.id)))
watch(observedObjects,rows=>{if(!rows.some(o=>o.id===subject.value))subject.value=rows[0]?.id||''},{immediate:true})
const values=computed(()=>props.objects.filter(o=>typeof o.properties[field.value]==='number'&&Number.isFinite(o.properties[field.value])))
const counts=computed(()=>{const grouped=new Map<string,number>();for(const o of props.objects)grouped.set(o.typeName,(grouped.get(o.typeName)||0)+1);return [...grouped].map(([name,value])=>({name,value}))})
const bars=computed(()=>mode.value==='count'?counts.value:values.value.map(o=>({name:o.name,value:o.properties[field.value] as number,id:o.id})))
const maxBar=computed(()=>Math.max(1,...bars.value.map(b=>Math.abs(b.value))))
const series=computed(()=>props.observations.filter(o=>o.objectId===subject.value&&Number.isFinite(Date.parse(o.timestamp))&&(!goodOnly.value||o.quality==='good')).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)))
const times=computed(()=>series.value.map(r=>Date.parse(r.timestamp)))
const range=(arr:number[])=>{const min=Math.min(...arr),max=Math.max(...arr);return {min,max,span:max-min||1}}
const linePoints=computed(()=>{if(!series.value.length)return [];const x=range(times.value),y=range(series.value.map(r=>r.value));return series.value.map((r,i)=>({x:60+(times.value[i]-x.min)/x.span*620,y:260-(r.value-y.min)/y.span*210,row:r}))})
const scatter=computed(()=>{const rows=props.objects.filter(o=>[o.properties[field.value],o.properties[other.value]].every(v=>typeof v==='number'&&Number.isFinite(v)));if(!rows.length)return [];const x=range(rows.map(o=>o.properties[field.value] as number)),y=range(rows.map(o=>o.properties[other.value] as number));return rows.map(o=>({o,x:60+((o.properties[field.value] as number)-x.min)/x.span*620,y:260-((o.properties[other.value] as number)-y.min)/y.span*210}))})
const sum=computed(()=>values.value.reduce((n,o)=>n+(o.properties[field.value] as number),0))
</script>
<template><section class="charts card"><div class="chart-controls"><label>图表形式<AppSelect v-model="mode" aria-label="图表形式" :options="[{value:'count',label:'对象数量 · 柱状图'},{value:'value',label:'属性数值 · 条形图'},{value:'scatter',label:'属性对比 · 散点图'},{value:'time',label:'SOC观测 · 时间序列'}]"/></label><label v-if="['value','scatter'].includes(mode)">数值属性<AppSelect v-model="field" aria-label="图表数值属性" :options="options"/></label><label v-if="mode==='scatter'">纵轴属性<AppSelect v-model="other" aria-label="散点纵轴属性" :options="options"/></label><label v-if="mode==='time'">观测对象<AppSelect v-model="subject" aria-label="观测对象" :options="observedObjects.map(o=>({value:o.id,label:o.name}))"/></label></div>
<template v-if="mode==='count'||mode==='value'"><h3>{{mode==='count'?'当前筛选内的对象数量':options.find(o=>o.value===field)?.label}}</h3><p v-if="mode==='value'&&values.length" class="muted">有值 {{values.length}} 个 · 缺值 {{objects.length-values.length}} 个 · 最小 {{Math.min(...values.map(o=>o.properties[field] as number))}} · 最大 {{Math.max(...values.map(o=>o.properties[field] as number))}} · 平均 {{(sum/values.length).toFixed(2)}}（按原字段单位）</p><p v-if="!bars.length" class="empty">当前筛选没有可绘制的数值。</p><div v-for="(bar,i) in bars" :key="i" class="bar-row"><span>{{bar.name}}</span><div class="bar-track"><div :style="{width:Math.abs(bar.value)/maxBar*100+'%',background:bar.value<0?'#bd4c5a':'#346fe1'}"></div></div><strong>{{bar.value}}</strong></div><p v-if="mode==='value'" class="muted">条长表示数值绝对大小；负数以红色和负号标识。不同属性不混合汇总。</p></template>
<template v-else-if="mode==='time'"><label class="quality"><input v-model="goodOnly" type="checkbox">只看质量有效的观测</label><p class="muted">历史采样值，非实时数据，也不代表系统加权 SOC。当前 {{series.length}} 个采样点。</p><svg v-if="linePoints.length" viewBox="0 0 740 340" role="img" aria-label="SOC历史观测折线图"><path d="M60 35V270H700" fill="none" stroke="#a2b4c8"/><polyline :points="linePoints.map(p=>p.x+','+p.y).join(' ')" fill="none" stroke="#346fe1" stroke-width="3"/><g v-for="(p,i) in linePoints" :key="i"><circle :cx="p.x" :cy="p.y" r="5" fill="#346fe1"><title>{{p.row.timestamp}} · {{p.row.value}}{{p.row.unit}} · {{p.row.quality}}</title></circle><text :x="p.x" :y="p.y-12" text-anchor="middle">{{p.row.value}}{{p.row.unit}}</text></g><text x="50" y="55" text-anchor="end">{{Math.max(...series.map(r=>r.value))}}</text><text x="50" y="265" text-anchor="end">{{Math.min(...series.map(r=>r.value))}}</text><text x="60" y="297">{{series[0]?.timestamp}}</text><text v-if="series.length>1" x="700" y="320" text-anchor="end">{{series.at(-1)?.timestamp}}</text></svg><p v-else class="empty">当前对象没有符合条件的观测。</p><div v-if="series.length" class="scroll"><table><thead><tr><th>采样时间</th><th>SOC</th><th>质量</th><th>来源</th></tr></thead><tbody><tr v-for="(r,i) in series" :key="i"><td>{{r.timestamp}}</td><td>{{r.value}}{{r.unit}}</td><td>{{r.quality}}</td><td>{{r.source}}</td></tr></tbody></table></div></template>
<template v-else><p class="muted">横轴：{{options.find(o=>o.value===field)?.label}}；纵轴：{{options.find(o=>o.value===other)?.label}}。悬停查看原始值，点击选择对象。</p><svg v-if="scatter.length" viewBox="0 0 740 340" role="img" aria-label="对象属性散点图"><path d="M60 35V270H700" fill="none" stroke="#a2b4c8"/><text x="60" y="298">{{Math.min(...scatter.map(p=>p.o.properties[field] as number))}}</text><text x="680" y="298" text-anchor="end">{{Math.max(...scatter.map(p=>p.o.properties[field] as number))}}</text><text x="50" y="55" text-anchor="end">{{Math.max(...scatter.map(p=>p.o.properties[other] as number))}}</text><text x="50" y="265" text-anchor="end">{{Math.min(...scatter.map(p=>p.o.properties[other] as number))}}</text><g v-for="p in scatter" :key="p.o.id"><circle :cx="p.x" :cy="p.y" r="7" fill="#346fe1" tabindex="0" role="button" :aria-label="p.o.name" @click="emit('select',p.o.id)" @keydown.enter="emit('select',p.o.id)"><title>{{p.o.name}}：{{p.o.properties[field]}} / {{p.o.properties[other]}}</title></circle><text :x="p.x" :y="p.y-12" text-anchor="middle">{{p.o.name}}</text></g></svg><p v-else class="empty">没有同时具有两个数值属性的对象。</p></template></section></template>
<style scoped>.chart-controls{display:flex;gap:16px;flex-wrap:wrap}.chart-controls label{min-width:210px;flex:1}.charts svg{width:100%;max-height:400px;overflow:visible;margin:18px 0 32px}.charts text{font-size:12px;fill:#455d76}.bar-row{display:grid;grid-template-columns:minmax(100px,180px) 1fr 70px;gap:16px;align-items:center;margin:16px 0}.bar-track{background:var(--paper-2);height:22px;border-radius:4px;overflow:hidden}.bar-track>div{height:100%;min-width:0}.quality{display:flex;align-items:center;gap:8px}.quality input{width:auto}.charts circle[role=button]{cursor:pointer}@media(max-width:600px){.bar-row{grid-template-columns:100px 1fr 50px;gap:8px}}</style>
