<script setup lang="ts">
import {computed,ref,watch,onMounted,onBeforeUnmount} from 'vue'
import cytoscape from 'cytoscape'
import type {Core,CollectionReturnValue} from 'cytoscape'
import type {KnowledgeNode,KnowledgeEdge,KnowledgeKind} from './knowledgeTypes'
import {KNOWLEDGE_CANVAS, KNOWLEDGE_KIND_FILL} from '../shared/graphStyle'
import AppSelect from '../shared/AppSelect.vue'
const props=defineProps<{nodes:KnowledgeNode[];edges:KnowledgeEdge[];selectedId:string;showProperties:boolean}>()
const emit=defineEmits<{select:[id:string];selectEdge:[id:string]}>()
const canvas=ref<HTMLElement>(),layout=ref('breadthfirst'),selection=ref(''),edgeSelection=ref(''),neighborsOnly=ref(false)
const kinds:Record<KnowledgeKind,{label:string;color:string;shape:string}>={object:{label:'对象类型',color:KNOWLEDGE_KIND_FILL.object,shape:'round-rectangle'},property:{label:'属性',color:KNOWLEDGE_KIND_FILL.property,shape:'ellipse'},valueType:{label:'值类型',color:KNOWLEDGE_KIND_FILL.valueType,shape:'hexagon'},function:{label:'计算定义',color:KNOWLEDGE_KIND_FILL.function,shape:'round-rectangle'},action:{label:'动作定义',color:KNOWLEDGE_KIND_FILL.action,shape:'round-rectangle'},interface:{label:'接口定义',color:KNOWLEDGE_KIND_FILL.interface,shape:'diamond'},mapping:{label:'项目数据映射',color:KNOWLEDGE_KIND_FILL.mapping,shape:'barrel'}}
const legend=computed(()=>Object.entries(kinds).filter(([kind])=>props.nodes.some(n=>n.kind===kind)))
const validEdges=computed(()=>{const ids=new Set(props.nodes.map(n=>n.id));return props.edges.filter(e=>ids.has(e.source)&&ids.has(e.target))})
const selected=computed(()=>props.nodes.find(n=>n.id===selection.value))
let cy:Core|undefined,observer:ResizeObserver|undefined
const nodeId=(id:string)=>'node:'+id
const edgeId=(id:string)=>'edge:'+id
function fitElements(elements:CollectionReturnValue,padding=50){if(!cy||!elements.length)return;cy.fit(elements,padding);if(cy.zoom()>1.1)cy.zoom(1.1);cy.center(elements)}
function fit(){if(cy)fitElements(cy.elements(':visible'))}
function arrange(){if(!cy||!props.nodes.length)return;cy.elements(':visible').layout({name:layout.value,animate:false,fit:false,padding:50,nodeDimensionsIncludeLabels:true,...(layout.value==='breadthfirst'?{directed:true,spacingFactor:props.nodes.length<=4?1:1.7}:{}),...(layout.value==='cose'?{randomize:false,nodeRepulsion:()=>90000,idealEdgeLength:()=>260,componentSpacing:160}:{}),...(layout.value==='grid'?{avoidOverlap:true,spacingFactor:1.3}:{}),...(layout.value==='circle'?{avoidOverlap:true,spacingFactor:1.3}:{}),stop:()=>fit()} as any).run()}
function applySelection(){if(!cy)return;cy.elements().removeClass('focused faded edge-focused').style('display','element');const node=cy.getElementById(nodeId(selection.value));const edge=cy.getElementById(edgeId(edgeSelection.value));if(node.length){const vicinity=node.closedNeighborhood();node.addClass('focused');cy.elements().difference(vicinity).addClass('faded');if(neighborsOnly.value)cy.elements().difference(vicinity).style('display','none')}else if(edge.length){edge.addClass('edge-focused');cy.elements().difference(edge.union(edge.connectedNodes())).addClass('faded')}else neighborsOnly.value=false}
function select(id:string,notify=true){selection.value=id;edgeSelection.value='';applySelection();if(notify)emit('select',id)}
function selectEdge(id:string){selection.value='';edgeSelection.value=id;neighborsOnly.value=false;applySelection();emit('selectEdge',id)}
function reset(){neighborsOnly.value=false;select('');arrange()}
function focus(){if(!cy)return;const n=cy.getElementById(nodeId(selection.value));if(n.length)fitElements(n.closedNeighborhood(),65);else fit()}
function zoom(factor:number){if(cy)cy.zoom({level:Math.max(.04,Math.min(3,cy.zoom()*factor)),renderedPosition:{x:cy.width()/2,y:cy.height()/2}})}
function label(n:KnowledgeNode){const head=`${n.label}\n〔${kinds[n.kind].label}〕`;if(!props.showProperties||n.kind!=='object'||!n.properties?.length)return head;const rows=n.properties.slice(0,4).map(p=>'· '+p.label);if(n.properties.length>4)rows.push(`… 共 ${n.properties.length} 项属性`);return head+'\n'+rows.join('\n')}
function update(){if(!cy)return;cy.elements().remove();const seen=new Set<string>();cy.add(props.nodes.filter(n=>{if(seen.has(n.id))return false;seen.add(n.id);return true}).map(n=>({data:{id:nodeId(n.id),resourceId:n.id,label:label(n),kind:n.kind,color:kinds[n.kind].color,shape:kinds[n.kind].shape,height:props.showProperties&&n.kind==='object'&&n.properties?.length?65+Math.min(n.properties.length+1,5)*21:66}})));const edgeSeen=new Set<string>();cy.add(validEdges.value.filter(e=>{if(edgeSeen.has(e.id))return false;edgeSeen.add(e.id);return true}).map(e=>({data:{id:edgeId(e.id),resourceId:e.id,source:nodeId(e.source),target:nodeId(e.target),label:e.label,kind:e.kind}})));if(selection.value&&!seen.has(selection.value))selection.value='';if(edgeSelection.value&&!edgeSeen.has(edgeSelection.value))edgeSelection.value='';applySelection();arrange()}
function exportPng(){if(!cy||!props.nodes.length)return;const a=document.createElement('a');a.href=cy.png({full:true,bg:KNOWLEDGE_CANVAS.exportBg,scale:2,maxWidth:6000,maxHeight:6000});a.download='完整本体模型.png';a.click()}
function keydown(e:KeyboardEvent){if(e.target!==canvas.value||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key.toLowerCase()==='f'){e.preventDefault();e.stopPropagation();focus()}else if(e.key==='Escape'){e.preventDefault();e.stopPropagation();neighborsOnly.value=false;select('')}}
watch(()=>[props.nodes,props.edges,props.showProperties],update,{deep:true})
watch(()=>props.selectedId,id=>{if(props.edges.some(e=>e.id===id)){selection.value='';edgeSelection.value=id;neighborsOnly.value=false;applySelection()}else if(id!==selection.value)select(id,false)})
watch(neighborsOnly,()=>{applySelection();arrange()})
watch(layout,arrange)
onMounted(()=>{cy=cytoscape({container:canvas.value,elements:[],minZoom:.04,maxZoom:3,wheelSensitivity:.18,boxSelectionEnabled:false,autounselectify:true,style:[{selector:'node',style:{'background-color':'data(color)',shape:'data(shape)' as any,label:'data(label)',width:210,height:'data(height)','font-size':14,'text-valign':'center','text-halign':'center','text-wrap':'wrap','text-max-width':'192px','line-height':1.5,color:KNOWLEDGE_CANVAS.nodeText,'border-width':1.5,'border-color':KNOWLEDGE_CANVAS.nodeBorder,padding:'10px'}},{selector:'edge',style:{width:1.7,'line-color':KNOWLEDGE_CANVAS.edgeLine,'target-arrow-color':KNOWLEDGE_CANVAS.edgeLine,'target-arrow-shape':'triangle','curve-style':'bezier',label:'data(label)','font-size':12,color:KNOWLEDGE_CANVAS.edgeLabel,'text-background-color':KNOWLEDGE_CANVAS.labelBg,'text-background-opacity':.95,'text-background-padding':'4px','text-rotation':'autorotate','text-wrap':'wrap','text-max-width':'150px'}},{selector:'edge[kind = "dependency"]',style:{'line-style':'dashed','line-color':KNOWLEDGE_CANVAS.edgeDependency,'target-arrow-color':KNOWLEDGE_CANVAS.edgeDependency,'target-arrow-shape':'chevron'}},{selector:'.focused',style:{'border-color':KNOWLEDGE_CANVAS.focused,'border-width':3}},{selector:'.edge-focused',style:{width:3,'line-color':KNOWLEDGE_CANVAS.focused,'target-arrow-color':KNOWLEDGE_CANVAS.focused,color:KNOWLEDGE_CANVAS.focusedLabel}},{selector:'.faded',style:{opacity:.2}}]});cy.on('tap','node',e=>{canvas.value?.focus({preventScroll:true});select(e.target.data('resourceId'))});cy.on('tap','edge',e=>{canvas.value?.focus({preventScroll:true});selectEdge(e.target.data('resourceId'))});cy.on('tap',e=>{if(e.target===cy){canvas.value?.focus({preventScroll:true});select('')}});if(props.edges.some(e=>e.id===props.selectedId))edgeSelection.value=props.selectedId;else selection.value=props.selectedId;update();observer=new ResizeObserver(()=>cy?.resize());if(canvas.value)observer.observe(canvas.value)})
onBeforeUnmount(()=>{observer?.disconnect();cy?.destroy();cy=undefined})
</script>
<template>
<section class="knowledge-canvas">
  <div class="kc-toolbar"><div class="kc-layout"><AppSelect v-model="layout" aria-label="知识模型布局" :options="[{value:'breadthfirst',label:'层级布局'},{value:'cose',label:'力导向布局'},{value:'circle',label:'环形布局'},{value:'grid',label:'网格布局'}]"/></div><button type="button" @click="fit">适应全图</button><button type="button" aria-label="放大模型图" @click="zoom(1.25)">＋</button><button type="button" aria-label="缩小模型图" @click="zoom(.8)">−</button><button type="button" :disabled="!selected" @click="focus">聚焦所选</button><label><input v-model="neighborsOnly" type="checkbox" :disabled="!selected">仅一跳关联</label><button type="button" @click="reset">重置</button><button type="button" :disabled="!nodes.length" @click="exportPng">导出 PNG</button></div>
  <div class="kc-legend"><span v-for="[key,item] in legend" :key="key"><i :style="{background:item.color}"></i>{{item.label}}</span><span><b class="kc-solid"></b>业务链接</span><span><b class="kc-dashed"></b>模型依赖</span><span class="kc-count">{{nodes.length}} 个节点 · {{validEdges.length}} 条连线</span></div>
  <div class="kc-stage"><div ref="canvas" class="kc-surface" tabindex="0" aria-label="只读完整本体模型图，点击节点或连线查看详情，F 聚焦，Esc 清除选择" @keydown="keydown"></div><div v-if="!nodes.length" class="kc-empty">当前范围没有可展示的模型定义，请调整显示范围或筛选条件。</div><div class="canvas-hint">只读模型 · 拖动平移 / 调整节点位置 · 滚轮缩放 · F 聚焦 · Esc 取消选择</div></div>
</section>
</template>
<style scoped>
.knowledge-canvas{background:var(--paper);border:1px solid var(--line);border-radius:var(--r-md);overflow:hidden;color:var(--ink)}.kc-toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:8px;padding:12px;border-bottom:1px solid var(--line)}.kc-toolbar button{padding:7px 10px;font-size:13px}.kc-layout{width:155px}.kc-layout :deep(.app-select){margin-top:0}.kc-toolbar label{display:flex;align-items:center;gap:6px;font-size:13px;margin:0 5px}.kc-toolbar input{width:auto;margin:0}.kc-legend{display:flex;gap:12px;align-items:center;flex-wrap:wrap;padding:12px 16px;font-size:12px;color:var(--muted)}.kc-legend span{display:flex;gap:6px;align-items:center}.kc-legend i{width:12px;height:12px;border:1px solid var(--line-2);border-radius:var(--r-sm)}.kc-solid,.kc-dashed{display:block;width:22px;border-top:2px solid v-bind('KNOWLEDGE_CANVAS.edgeLine')}.kc-dashed{border-top-style:dashed}.kc-count{margin-left:auto}.kc-stage{position:relative;min-width:0}.kc-surface{height:600px;min-height:560px;width:100%;background:radial-gradient(var(--grid) 1px,transparent 1px);background-size:18px 18px}.kc-surface:focus-visible{outline:2px solid var(--focus);outline-offset:-2px}.kc-surface+.canvas-hint{width:fit-content}.kc-empty{position:absolute;inset:0;display:grid;place-items:center;padding:32px;text-align:center;color:var(--faint);pointer-events:none}@media(max-width:850px){.kc-count{margin-left:0}.kc-surface{height:560px}}
</style>
